import { mkdir, writeFile, copyFile, cp, readFile, access } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
const links = [['product','產品介紹'],['cases','精選範例'],['about','關於我們'],['faq','常見問題'],['comparison','組合屋比較'],['contact','申請場勘']];
const arrow = '<span aria-hidden="true">→</span>';
const button = (href,text,outline=false) => `<a class="button ${outline?'outline':''}" href="${href}">${text}${arrow}</a>`;
const heading = (en,title,href,label='了解更多') => `<div class="section-title"><div><div class="eyebrow">${en}</div><h2>${title}</h2></div>${href?`<a class="text-link" href="${href}">${label}${arrow}</a>`:''}</div>`;
const cards = [
  {id:'retreat',category:'living',image:'garden.jpg',title:'把日常，安放在自然裡',type:'自然系住宅',sub:'開闊採光・庭院生活',no:'01'},
  {id:'weekend',category:'living',image:'interior.jpg',title:'留一個週末，給自己',type:'週末休憩空間',sub:'溫暖木質・自在起居',no:'02'},
  {id:'studio',category:'work',image:'studio.jpg',title:'工作，也有喜歡的風景',type:'獨立工作室',sub:'彈性配置・工作與生活',no:'03'}
];
const card = item => `<a class="card" data-category="${item.category}" href="cases.html#${item.id}"><figure><img class="photo photo-${item.id}" src="assets/${item.image}" alt="${item.type}，官方素材照片" loading="lazy" width="800" height="600"></figure><div class="meta"><span>SPACE IDEA ${item.no} / ${item.type}</span>${arrow}</div><h3>${item.title}</h3><p>${item.sub}</p></a>`;
const steps = [['相互認識','分享用途、基地位置與理想中的生活。'],['基地場勘','了解現地環境、進出動線及施工條件。'],['規劃提案','討論格局、材料、預算與施作範圍。'],['確認與施作','依確認的設計與合約安排生產、施工。'],['驗收與交付','逐項確認完成內容與後續維護方式。']];
const stepsHtml = `<div class="steps">${steps.map(([title,desc],i)=>`<div class="step"><span class="number">0${i+1}</span><h3>${title}</h3><p>${desc}</p></div>`).join('')}</div>`;
const features = `<div class="features"><div class="feature"><span class="number">01 / STRUCTURE</span><h3>從結構，理解安心</h3><p>從柱樑配置、構件接合到基礎設計，逐一討論空間背後的重要細節。</p></div><div class="feature"><span class="number">02 / COMFORT</span><h3>讓舒適回到日常</h3><p>將採光、通風、隔熱與防水納入規劃，回應生活的真實需要。</p></div><div class="feature"><span class="number">03 / FLEXIBILITY</span><h3>為生活保留彈性</h3><p>依基地與使用需求討論格局，讓居住、休憩和工作的想像有適合的位置。</p></div></div>`;
const cta = `<section class="contact-band"><div class="eyebrow">LET’S BUILD YOUR EVERYDAY</div><h2>家的想像，從一次對話開始。</h2><p>無論已有基地，或還在描繪理想生活，我們都想聽聽你的想法。</p>${button('contact.html','開始場勘諮詢')}</section>`;
function shell(id,title,body){return `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="易立構 EASY GO，以簡約、舒適、安心為出發點，探索組合屋與彈性生活空間。${title}"><meta name="theme-color" content="#293c44"><title>${title}｜易立構 EASY GO</title><link rel="icon" href="assets/logo.png"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head><body><a class="skip" href="#main">跳至主要內容</a><header class="header"><div class="header-inner"><a class="logo" href="index.html" aria-label="易立構，回首頁"><img src="assets/logo.png" width="168" height="65" alt="易立構 EASY GO"></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" type="button">選單 ☰</button><nav class="nav" id="main-nav" aria-label="主要導覽">${links.map(([key,label])=>`<a href="${key}.html" ${key===id?'aria-current="page"':''} ${key==='contact'?'class="nav-cta"':''}>${label}</a>`).join('')}</nav></div></header><main id="main">${body}</main><footer class="footer"><div class="footer-top"><a class="logo" href="index.html"><img src="assets/logo.png" width="145" height="61" alt="易立構 EASY GO"></a><div class="footer-links">${links.map(([key,label])=>`<a href="${key}.html">${label}</a>`).join('')}</div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} 易立構 EASY GO. 簡約・舒適・安心</span><span>網站設計提案｜住宅照片為情境示意，非施工實績</span><a href="#main">回到頂端 ↑</a></div></footer></body></html>`;}
const pageHead = (en,title,desc) => `<div class="wrap page-head"><div class="breadcrumb"><a href="index.html">首頁</a> / ${title}</div><div class="eyebrow muted">${en}</div><h1>${title}</h1><p>${desc}</p></div>`;
const pages = {};
pages.index = shell('index','為生活，留一點餘白',`<section class="hero" aria-label="生活空間主視覺"><img src="assets/house.jpg" class="photo" alt="草地與椰樹環繞的木質組合屋，連接開闊露台" width="800" height="600" fetchpriority="high"><div class="hero-copy"><div class="eyebrow">EASY GO · A SIMPLE WAY OF LIVING</div><h1>為生活，<br>留一點餘白。</h1><p>一個家的可能，從簡單開始。</p><a class="hero-link" href="product.html">探索易立構的家 ${arrow}</a></div><div class="hero-bottom"><span>01 <span class="line"></span> THE WAY WE LIVE</span><span>木質住宅・庭院日常<br>SCROLL TO EXPLORE ↓</span></div></section>
<section class="intro wrap"><div class="eyebrow muted">SIMPLE. COMFORTABLE. REASSURING.</div><h2>好好生活，其實可以很簡單。</h2><p>讓空間回歸生活，讓每一分安排都有意義。<br>從結構、採光到日常的使用，我們在意家的每一個細節。<br>易立構，和你一起描繪簡約、舒適、安心的生活。</p><a class="text-link" href="about.html">認識易立構 ${arrow}</a></section>
<section class="section soft"><div class="wrap">${heading('SPACES & STORIES','家的不同模樣','cases.html','探索精選範例')}<div class="grid">${cards.map(card).join('')}</div><p class="section-note">空間提案與照片皆為規劃示意，實際設計依基地條件與需求確認。</p></div></section>
<section class="section"><div class="wrap"><div class="split"><img class="photo photo-interior" src="assets/interior.jpg" alt="木質室內與大片玻璃門窗，將田野景色帶進生活" loading="lazy" width="800" height="450"><div><div class="eyebrow muted">MADE FOR EVERYDAY</div><h2>看得見的簡約。<br>看不見的用心。</h2><p>好的空間，不只是外觀。<br>從結構到材質，從生產到現場組裝，<br>每一個選擇，都回到「如何住得更好」。</p><a class="text-link" href="product.html">了解產品與結構 ${arrow}</a></div></div>${features}</div></section>
<section class="wrap comparison"><div><div class="eyebrow muted">KNOW THE DIFFERENCE</div><h2>選擇之前，把差異看清楚。</h2><p>從柱樑、樓板到施工範圍，用相同條件比較組合屋方案。</p></div>${button('comparison.html','查看組合屋比較',true)}</section>
<section class="section"><div class="wrap">${heading('YOUR HOME, STEP BY STEP','一步一步，靠近理想的家','contact.html','開始規劃')}${stepsHtml}</div></section>
<section class="section soft"><div class="wrap form-layout"><div><div class="eyebrow muted">LET’S TALK</div><h2>你對家的想像，<br>我們想聽。</h2><p>填寫初步需求，整理一份屬於你的場勘諮詢單。</p><a class="text-link" href="contact.html">了解場勘流程 ${arrow}</a></div>${inquiryForm()}</div></section>`);
pages.product = shell('product','產品介紹',`${pageHead('OUR APPROACH','簡單的空間，完整的思考。','從結構到生活方式，讓每一個規劃都有依據。')}<section class="section"><div class="wrap"><div class="split"><img class="photo photo-house" src="assets/house.jpg" alt="木質組合屋外觀與前方露台" width="800" height="600"><div><div class="eyebrow muted">01 / STRUCTURE</div><h2>家的起點，<br>是把基礎做好。</h2><p>規劃從基地條件、用途與尺度開始。柱樑、樓板、接合與基礎需要一起考量，才能把喜歡的空間轉化成具體方案。</p><p>結構尺寸、材料等級與性能數據應以個案設計圖說及正式文件為準。</p></div></div>${features}</div></section><section class="section soft"><div class="wrap">${heading('HOW IT COMES TOGETHER','從圖面，到現場')}<div class="steps">${[['需求與設計','確認用途、格局與配置。'],['材料與構件','依核定方案安排材料及製作。'],['生產與檢查','核對構件尺寸與製作品質。'],['現場組裝','依現地條件安排施工順序。'],['完成與驗收','檢查施作範圍並交付紀錄。']].map(([t,p],i)=>`<div class="step"><span class="number">0${i+1}</span><h3>${t}</h3><p>${p}</p></div>`).join('')}</div></div></section><section class="section"><div class="wrap">${heading('SPACE PLANNING','從用途，找到適合的模型')}<div class="model-grid">${[['日常居所','起居、收納與休息的平衡，從家庭人數和日常習慣開始。'],['休憩小屋','把窗外風景帶進生活，為假日留下舒適的停留空間。'],['工作空間','依接待、辦公或創作需求，安排採光、動線和設備。']].map(([t,p])=>`<article class="model"><h3>${t}</h3><p>${p}</p><a class="text-link" href="contact.html">討論配置與預算 ${arrow}</a></article>`).join('')}</div><p class="section-note">以上為用途方向，非定型產品規格。預算須依面積、基地、基礎、材料、運輸、水電與裝修範圍估算。</p><div class="comparison"><div><h2>差異，從具體項目開始比較。</h2><p>完整理解報價包含的內容，才能做出適合自己的選擇。</p></div>${button('comparison.html','查看比較重點',true)}</div></div></section>${cta}`);
pages.cases = shell('cases','精選範例',`${pageHead('SPACES & STORIES','家的不同模樣','從居住、休憩到工作，探索空間與生活的不同可能。以下為概念提案，非已完工案例。')}<section class="section"><div class="wrap"><div class="filters" aria-label="篩選空間用途"><button class="filter" data-filter="all" aria-pressed="true">全部提案</button><button class="filter" data-filter="living" aria-pressed="false">居住與休憩</button><button class="filter" data-filter="work" aria-pressed="false">工作空間</button></div><p class="section-note" id="filter-status" role="status">顯示 3 個空間提案</p><div class="grid">${cards.map(card).join('')}</div>${cards.map(item=>`<article class="case-detail" id="${item.id}"><div class="eyebrow muted">SPACE IDEA ${item.no} / ${item.type}</div><h2>${item.title}</h2><p>${item.id==='retreat'?'以庭院連結起居空間，從家庭成員的生活習慣安排公共與私密區域。':item.id==='weekend'?'用自然材質與柔和採光，描繪可以放慢步調的休憩場所。':'讓工作與生活各有位置，依設備、訪客與專注工作的需求安排動線。'}此提案僅呈現空間方向，面積、材料、造價與工期須另行確認。</p><img src="assets/${item.image}" class="photo photo-${item.id}" alt="${item.type}，官方素材照片" width="800" height="600" loading="lazy"><p><a class="text-link" href="contact.html">討論類似的空間需求 ${arrow}</a></p></article>`).join('')}</div></section>${cta}`);
pages.about = shell('about','關於我們',`${pageHead('ABOUT EASY GO','簡約・舒適・安心','易立構，從日常生活出發，思考空間應有的樣子。')}<section class="section"><div class="wrap split"><img class="photo photo-lounge" src="assets/lounge.jpg" alt="自然採光下的沙發與木地板起居角落" width="640" height="480"><div><div class="eyebrow muted">OUR PHILOSOPHY</div><h2>少一些繁複，<br>多一些生活。</h2><p>簡約，是把需要的留下；舒適，是讓日常自在發生；安心，是願意把看不見的細節說清楚。</p><p>這是易立構網站所傳達的生活提案，也是每一次空間討論的出發點。</p></div></div></section><section class="section soft"><div class="wrap">${heading('BRAND & DOCUMENTS','認識品牌的每一步')}<div class="grid"><article class="feature"><span class="number">01 / HISTORY</span><h3>品牌大事紀</h3><p>品牌沿革與里程碑整理中，將於正式資料確認後公開。</p></article><article class="feature"><span class="number">02 / PATENTS</span><h3>專利資料</h3><p>專利名稱、證號與適用範圍待正式文件補齊後展示。</p></article><article class="feature"><span class="number">03 / CONTACT</span><h3>聯絡資訊</h3><p>正式電話、電子信箱及地址待確認。你可以先整理空間需求，產生場勘諮詢單。</p><a class="text-link" href="contact.html">填寫需求 ${arrow}</a></article></div></div></section>${cta}`);
const questions = [['還沒有土地，可以先了解嗎？','可以先整理用途、希望的空間規模與預算方向。具體設計與施工方案仍需要配合基地條件評估。'],['組合屋的價格如何估算？','報價通常需要確認面積、材料、基礎、運輸、現場組裝、水電及裝修範圍。本站未提供固定價格，請先整理需求再進行個案估算。'],['場勘前要準備哪些資料？','建議備妥基地所在地區、現況照片、希望的用途、預計使用人數，以及已知的道路或施工限制。初次填寫可先提供縣市與地區。'],['可以調整格局與外觀嗎？','可先提出格局、開窗、外觀與設備需求，是否適用需依選定系統、結構及基地條件確認。'],['從規劃到完成需要多久？','設計確認、材料安排、基地工程與現場條件都會影響時程。實際工期須在施工範圍確認後排定。'],['網站照片都是易立構的完工案例嗎？','本站照片選自提供的官方素材，空間名稱與用途文案為設計提案；個別照片的案名、地點與施工資訊，仍待正式案例資料確認。'],['填寫表單就完成場勘預約了嗎？','尚未。此版本會在你的裝置產生可下載的諮詢單，不會送出資料或保留預約。正式聯絡管道與表單收件服務接上後，才能確認場勘安排。']];
pages.faq = shell('faq','常見問題',`${pageHead('QUESTIONS & ANSWERS','你想知道的，我們一起釐清。','開始規劃之前，先了解空間、預算與場勘的基本問題。')}<section class="section"><div class="wrap prose faq">${questions.map(([q,a],i)=>`<details ${i===0?'open':''}><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>${cta}`);
const comparisonRows = [['柱樑結構','材料等級、構件尺寸、接合方式','提供設計圖說、規格及適用的檢驗文件。'],['樓板與使用','樓板組成、用途及設計條件','以相同用途與設計條件核對，避免只比厚度。'],['牆面與屋頂','材料層次、隔熱與防水細節','列明材料規格及施工範圍。'],['基礎與基地','基礎工程、排水、現場整備','確認是否包含在報價與施作範圍內。'],['運輸與組裝','配送、吊裝、進出路線與現場施工','核對運輸條件、設備費用與額外費用。'],['水電與裝修','設備、管線、表面材料與收邊','確認交付標準及未包含的工作。'],['售後與文件','保固範圍、排除項目、聯繫方式','以正式合約、保固書及檢驗紀錄為依據。']];
pages.comparison = shell('comparison','組合屋比較',`${pageHead('MAKE AN INFORMED CHOICE','把差異看清楚，再做選擇。','大陸組合屋比較專區：先把規格與施工範圍放在相同基準上，避免僅依產地或外觀判斷。')}<section class="section"><div class="wrap">${heading('COMPARE THE DETAILS','從每個部位，確認真正的差異')}<p class="muted">目前未提供特定廠商的驗證資料，以下列出比較時應索取的項目，不代表已驗證的品牌優劣。</p><div class="table-scroll" role="region" aria-label="組合屋比較項目表" tabindex="0"><table><thead><tr><th scope="col">比較部位</th><th scope="col">向雙方確認的內容</th><th scope="col">判讀重點</th></tr></thead><tbody>${comparisonRows.map(row=>`<tr>${row.map((cell,i)=>i===0?`<th scope="row">${cell}</th>`:`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="prose"><h2>照片與影片之外，也要看條件。</h2><p>新聞或網路影片可能缺少完整的設計、施工與現場背景。比較時應核對來源、適用條件和技術文件，避免將單一事件套用到所有產品。</p><p>新聞、影片及產品對照資料待來源查證後補充。</p></div></div></section>${cta}`);
function inquiryForm(){return `<form id="inquiry-form"><div class="form-grid"><label class="field">姓名（必填）<input name="name" autocomplete="name" required maxlength="80" placeholder="請輸入姓名"></label><label class="field">聯絡電話（必填）<input name="phone" type="tel" autocomplete="tel" required maxlength="30" pattern="[+0-9() .\\-]{6,30}" title="請輸入 6 至 30 字元的電話號碼，可包含數字、空格、括號、加號與連字號" placeholder="請輸入聯絡電話"></label><label class="field">電子信箱<input name="email" type="email" autocomplete="email" maxlength="120" placeholder="you@example.com"></label><label class="field">基地縣市／地區（必填）<input name="location" autocomplete="address-level2" required maxlength="120" placeholder="例如：台中市北屯區"></label><label class="field full">規劃用途<select name="purpose"><option>日常住宅</option><option>週末休憩</option><option>工作空間</option><option>其他／尚在規劃</option></select></label><label class="field full">告訴我們你的想法<textarea name="message" maxlength="3000" placeholder="希望的空間大小、使用人數、基地現況，或你想先了解的問題……"></textarea></label></div><p class="form-info">目前提供諮詢單下載，尚未開放線上送件。填寫內容只用於產生本機檔案，不會傳送或儲存至伺服器。</p><button class="button" type="submit">產生諮詢單 ${arrow}</button><p class="status" id="form-status" role="status" aria-live="polite"></p></form>`;}
pages.contact = shell('contact','申請場勘',`${pageHead('PLAN YOUR SPACE','家的第一步，從你的想法開始。','整理初步需求，讓後續場勘與規劃討論更具體。')}<section class="section"><div class="wrap form-layout"><aside><div class="eyebrow muted">SITE CONSULTATION</div><h2>先認識基地，<br>再描繪生活。</h2><p>請提供基地所在地區與規劃用途。初期不需要完整設計圖，從現有的想法開始就好。</p><div class="feature"><h3>場勘前，可以先準備</h3><p>01　基地位置與現況照片<br>02　使用需求與預計人數<br>03　預算方向與期待時程<br>04　道路、地形及既有設施資訊</p></div><p>此版本尚未串接收件服務。產生諮詢單後請自行保存，正式聯络資訊待補充。</p><a class="text-link" href="faq.html">先看看常見問題 ${arrow}</a></aside>${inquiryForm()}</div></section><section class="section soft"><div class="wrap">${heading('WHAT HAPPENS NEXT','從需求，到交付')}${stepsHtml}</div></section>`);
pages.index = pages.index.replace(/(<section class="hero[^>]*>[\s\S]*?<img\b)[^>]*>/, '$1 src="assets/hero/064c6f25-f428-4624-90b1-db024db8bfd8.png" class="photo" alt="組合屋建築情境示意 1" width="1672" height="941" fetchpriority="high" decoding="async">');
// A fixed image frame allows responsive composition without duplicating assets.
pages.index = pages.index.replace(/(<section class="hero[^>]*>[\s\S]*?)(<img\b[^>]*>)/, (_, before, image) => before + '<div class="hero-image-frame">' + image.replace('<img ', '<img data-composition="center" ') + '</div>');
await mkdir(path.join(root,'dist/client'),{recursive:true});
await mkdir(path.join(root,'dist/server'),{recursive:true});
for(const [name,html] of Object.entries(pages)){
  await writeFile(path.join(root,`${name}.html`),html);
  await writeFile(path.join(root,'dist/client',`${name}.html`),html);
}
for(const file of ['styles.css','app.js']) await copyFile(path.join(root,file),path.join(root,'dist/client',file));
await cp(path.join(root,'assets'),path.join(root,'dist/client/assets'),{recursive:true});
await writeFile(path.join(root,'dist/server/index.js'),`export default { async fetch(request, env) { return env.ASSETS.fetch(request); } };\n`);
// Keep the existing archived preview in sync with the source build.
const archivedDist = path.join(root,'site/dist');
if (await access(archivedDist).then(() => true, () => false)) {
  await cp(path.join(root,'dist'), archivedDist, {recursive:true});
}
// Check every local page link, fragment, script and image in the generated website.
let checked=0;
for(const [name,html] of Object.entries(pages)){
  for(const [,href] of html.matchAll(/(?:href|src)="([^"]+)"/g)){
    if(/^(https?:|data:)/.test(href)) continue;
    const [file,fragment] = href.split('#');
    const target=path.join(root,file||`${name}.html`);
    await access(target);
    if(fragment){const content=await readFile(target,'utf8');if(!content.includes(`id="${fragment}"`))throw new Error(`Missing fragment: ${name}: ${href}`);}
    checked++;
  }
}
console.log(`Built ${Object.keys(pages).length} HTML pages. Verified ${checked} local links, fragments, scripts and images.`);
