import {mkdir,writeFile,copyFile,cp,readFile,access} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const variant='reference';
const nav=[['product','產品介紹'],['cases','精選範例'],['about','關於我們'],['faq','常見問題'],['comparison','組合屋比較'],['contact','申請場勘']];
const arrow='<span aria-hidden="true">↗</span>';
const button=(url,text,light=false)=>`<a class="button ${light?'secondary':''}" href="${url}">${text}${arrow}</a>`;
const link=(url,text)=>`<a class="text-link" href="${url}">${text}${arrow}</a>`;
const title=(en,heading,detail='')=>`<div class="section-heading"><div><p class="eyebrow">${en}</p><h2>${heading}</h2></div>${detail}</div>`;
const photo=(name,alt,cls='',priority=false)=>`<img class="photo ${cls}" src="assets/${name}.jpg" alt="${alt}" width="800" height="${name==='interior'?450:name==='lounge'?600:600}" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const projects=[
  {id:'residence',category:'living',image:'house',en:'RESIDENCE',title:'讓日常，有更好的尺度',type:'日常住宅',desc:'木質外觀與延伸露台，讓室內外有自然的連結。',alt:'木質組合屋與前方露台'},
  {id:'retreat',category:'living',image:'interior',en:'RETREAT',title:'一處，安靜下來的空間',type:'休憩空間',desc:'採光、通風與木質觸感，回到空間最單純的需要。',alt:'木質室內的大片玻璃門窗'},
  {id:'studio',category:'work',image:'studio',en:'WORKSPACE',title:'把專注，留給喜歡的事',type:'獨立工作室',desc:'從工作方式出發，規劃獨立而有彈性的使用空間。',alt:'獨立小屋的玻璃立面與入口'}
];
const cards=()=>`<div class="project-grid">${projects.map((p,i)=>`<a class="project" data-category="${p.category}" href="cases.html#${p.id}"><figure>${photo(p.image,p.alt)}</figure><div class="project-meta"><span>0${i+1} / ${p.en}</span>${arrow}</div><h3>${p.title}</h3><p>${p.type} · 空間提案</p></a>`).join('')}</div>`;
const steps=[['需求討論','分享用途、基地與預算方向。'],['基地場勘','確認現況、進出動線與施工條件。'],['規劃報價','討論格局、材料及施作範圍。'],['生產施工','依確認圖說與合約安排作業。'],['驗收交付','逐項檢查，說明維護與使用方式。']];
const processBlock=()=>`<ol class="steps">${steps.map(([t,p],i)=>`<li><span class="step-number">0${i+1}</span><h3>${t}</h3><p>${p}</p></li>`).join('')}</ol>`;
const advantages=[['結構，先於外觀','從柱樑、樓板到接合方式，逐項討論承載、使用條件與施作細節。'],['舒適，來自細節','採光、通風、隔熱與防水，在規劃之初就一起考量。'],['配置，回應需求','依基地尺寸與使用方式安排格局，讓每一處空間各得其所。']];
const features=()=>`<div class="feature-grid">${advantages.map(([t,p],i)=>`<article class="feature"><span class="eyebrow">0${i+1} / ${['STRUCTURE','COMFORT','FLEXIBILITY'][i]}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div>`;
const form=()=>`<form id="inquiry-form"><div class="form-grid"><label class="field">姓名 <span>必填</span><input name="name" required autocomplete="name" maxlength="80" placeholder="如何稱呼您"></label><label class="field">聯絡電話 <span>必填</span><input name="phone" type="tel" required autocomplete="tel" pattern="[+0-9() .\\-]{6,30}" maxlength="30" title="請輸入 6 至 30 個字元的電話號碼" placeholder="方便聯繫的電話"></label><label class="field">電子信箱<input name="email" type="email" autocomplete="email" maxlength="120" placeholder="you@example.com"></label><label class="field">基地縣市／地區 <span>必填</span><input name="location" required autocomplete="address-level2" maxlength="120" placeholder="例如：台中市新社區"></label><label class="field full">規劃用途<select name="purpose"><option>日常住宅</option><option>休憩空間</option><option>工作空間</option><option>其他／尚在評估</option></select></label><label class="field full">需求說明<textarea name="message" maxlength="3000" placeholder="預計坪數、使用人數、預算方向，或您想先了解的問題。"></textarea></label></div><p class="form-note">目前提供諮詢單下載，資料不會送出；下載後尚未完成場勘預約。</p><button class="button" type="submit">下載場勘諮詢單 ${arrow}</button><p id="form-status" class="status" role="status" aria-live="polite"></p></form>`;
const cta=()=>`<section class="cta"><div class="wrap cta-inner"><div><p class="eyebrow">START WITH A CONVERSATION</p><h2>好的空間，從一次對話開始。</h2></div>${button('contact.html','與我們討論需求',true)}</div></section>`;
function shell(id,pageTitle,body){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="易立構 EASY GO｜${pageTitle}。從結構、設計到生活需求，認識適合自己的組合屋空間。"><meta name="theme-color" content="#f5f4f0"><title>${pageTitle}｜易立構 EASY GO</title><link rel="icon" href="assets/logo.png"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="reference.css"><script defer src="app.js"></script></head><body class="${variant} page-${id}"><a class="skip" href="#main">跳至主要內容</a><header class="header"><div class="header-inner"><a class="logo" href="index.html" aria-label="易立構首頁"><img src="assets/logo.png" alt="易立構 EASY GO" width="156" height="65"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">選單 ☰</button><nav class="nav" id="main-nav" aria-label="主要導覽">${nav.map(([key,label])=>`<a href="${key}.html" ${key===id?'aria-current="page"':''} class="${key==='contact'?'nav-cta':''}">${label}${key==='contact'?arrow:''}</a>`).join('')}</nav></div></header><main id="main">${body}<section class="visual-banner"><div class="wrap"><p class="eyebrow">FROM STRUCTURE TO POSSIBILITY.</p><h2>有空間需求？<br>一起找到合適的方案。</h2>${button('contact.html','開始規劃')}</div></section></main><footer class="footer"><div class="wrap"><div class="footer-top"><div><a class="logo" href="index.html"><img src="assets/logo.png" width="156" height="65" alt="易立構 EASY GO"></a><p>以結構為本，讓空間回歸生活。</p></div><div class="footer-nav">${nav.map(([key,label])=>`<a href="${key}.html">${label}</a>`).join('')}</div><a class="back-top" href="#main" aria-label="回到頁首">↑</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} EASY GO 易立構</span><span>空間設計提案 · 官方素材照片／建築情境示意</span></div></div></footer></body></html>`;}
const pageHead=(en,h,desc)=>`<section class="page-head wrap"><p class="breadcrumb"><a href="index.html">首頁</a> / ${nav.find(([k,v])=>h===v)?.[1] || h.replaceAll('<br>','')}</p><p class="eyebrow">${en}</p><h1>${h}</h1><p class="lead">${desc}</p></section>`;
const comparisonRows=[['柱樑結構','材質等級、斷面尺寸、接合方式','索取個案結構圖說與相應資料'],['樓板系統','板材規格、支撐配置、使用載重','確認設計用途及樓板構造'],['牆體與屋頂','隔熱層、防水層、板材厚度','對照材料表及節點施工圖'],['基礎工程','地質、排水、基礎形式','確認現場評估與報價是否包含'],['運輸與吊裝','運輸路線、設備、現場組装','釐清吊裝條件與額外費用'],['水電與裝修','管線、設備及內外裝範圍','逐項列明標準配備與選配'],['售後與文件','保固範圍、驗收與維護','以正式合約和交付文件確認']];
const comparisonTable=(short=false)=>`<div class="table-scroll" tabindex="0" role="region" aria-label="組合屋規格比較重點"><table><thead><tr><th scope="col">比較部位</th><th scope="col">應確認的規格</th><th scope="col">評估方式</th></tr></thead><tbody>${comparisonRows.slice(0,short?3:undefined).map(([a,b,c])=>`<tr><th scope="row">${a}</th><td>${b}</td><td>${c}</td></tr>`).join('')}</tbody></table></div>`;
const structure=`<svg class="structure" viewBox="0 0 640 440" role="img" aria-labelledby="structure-title"><title id="structure-title">組合屋柱樑、樓板與屋頂分層概念示意，非施工圖</title><g fill="none" stroke="currentColor" stroke-width="2"><path d="M100 120 350 45 535 125 285 205Z" fill="#e8e8e3"/><path d="M100 142 285 226 535 145M100 120v22M285 205v21M535 125v20"/><path d="M110 210 350 135 525 213 285 289Z" stroke-dasharray="5 6"/><path d="M110 205v115M285 284v114M525 211v111M350 137v113" stroke-width="6"/><path d="M100 322 350 245 535 326 285 408Z" fill="#ddded8"/><path d="M100 338 285 423 535 341M100 322v16M285 408v15M535 326v15"/><path d="m350 275-204 63m252-42-204 64m252-42-204 64"/><path d="M440 80h140M525 250h55M455 386h125" stroke-width="1"/></g><g fill="currentColor" font-family="sans-serif" font-size="14"><text x="552" y="68">屋頂</text><text x="552" y="237">柱樑</text><text x="552" y="374">樓板</text><text x="45" y="420" font-size="11">STRUCTURE / CONCEPT ONLY</text></g></svg>`;
const pages={};
const heroIndependent=`<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">EASY GO / MODULAR SPACES</p><h1>好空間。<br>從<span>本質</span>開始。</h1><p class="hero-description">把複雜留給專業，把簡單留給生活。<br>從結構到細節，為每一種日常找到合適的空間。</p><div class="hero-actions">${button('product.html','認識易立構')}${link('cases.html','瀏覽空間提案')}</div><div class="hero-index"><span>01 — 03</span><span>STRUCTURE. SPACE. LIFE.</span></div></div><figure class="hero-visual">${photo('house','木質組合屋外觀與露台','',true)}<figcaption><span>SPACE STUDY / 01</span><span>日常住宅 · 木質與光</span></figcaption></figure></section><div class="principles wrap"><span>以結構為本</span><span>以需求為尺度</span><span>以生活為中心</span><a href="#spaces">往下探索 ↓</a></div>`;
const heroReference=`<section class="hero"><div class="hero-copy wrap"><p class="eyebrow">BUILD A BETTER SPACE</p><h1>不只是建築，<br>而是更好的<br class="mobile-break">空間解決方案。</h1><p class="hero-description">組合屋規劃・結構設計・空間配置<br>以專業，回應每一種生活需求。</p><div class="hero-actions">${button('product.html','查看產品方案')}${button('contact.html','聯絡我們',true)}</div><p class="hero-scroll">SCROLL TO EXPLORE <span>↓</span></p></div><figure class="hero-visual"><img src="assets/hero-courtyard.png" alt="以官方住宅照片製作的素色庭院建築情境示意" width="1672" height="941" fetchpriority="high" decoding="async"><figcaption><span>FROM STRUCTURE TO POSSIBILITY.</span><span>建築情境示意</span></figcaption></figure></section>`;

const iconPaths=['M5 28V14L20 4l15 10v14H5Zm10 0V17h10v11M11 12h18','M7 28V12h26v16H7Zm7-16V7h12v5M7 19h26M18 18v4h4v-4','M8 17h22v9H8Zm22 1h3a4 4 0 0 1 0 8h-3M8 31h25M13 6v6m7-6v6m7-6v6','M6 30V8h28v22H6Zm8-22v22m12-22v22M6 19h28','M5 30V13L20 5l15 8v17H5Zm9 0V17h12v13m-12-8h12m-12 4h12','m23 4-13 18h10l-3 14 13-19H20l3-13Z'];
const lineIcon=i=>`<svg class="line-icon" viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[i]}"></path></svg>`;
const productOverview=`<section class="section wrap products-overview">${title('OUR SOLUTIONS','多元空間方案<br>滿足不同日常需求','<p>從住宅到獨立工作室，從用途、基地與配置出發，規劃簡潔而實用的空間。</p>')}<div class="solution-grid">${[['house','日常住宅','起居・收納・家庭生活'],['studio','獨立工作室','辦公・創作・接待'],['interior','休憩空間','採光・木質・自在停留'],['lounge','彈性配置','依需求討論格局與設備']].map(([im,t,d])=>`<a class="solution" href="product.html#plans"><figure>${photo(im,t)}</figure><div><h3>${t}</h3><p>${d}</p><span class="solution-link">了解更多 →</span></div></a>`).join('')}</div></section><section class="applications-section"><div class="wrap applications"><div><p class="eyebrow">APPLICATION</p><h2>一個空間<br>多種可能</h2><p>以使用需求為核心，<br>找出適合每一種日常的配置。</p>${link('product.html#plans','探索空間用途')}</div><div class="application-grid">${['日常住宅','獨立辦公','休憩起居','創作工作室','收納空間','彈性用途'].map((t,i)=>`<a href="product.html#plans">${lineIcon(i)}<span>${t}</span></a>`).join('')}</div></div></section>`;

pages.index=shell('index','以結構為本，讓空間回歸生活',`${variant==='independent'?heroIndependent:heroReference}${productOverview}
<section class="section wrap" id="spaces">${title('01 / SELECTED SPACES','空間的樣子，<br class="desktop-break">由生活決定。',link('cases.html','所有空間提案'))}${cards()}<p class="note">照片選自官方素材；名稱與用途為設計提案，實際配置依基地與需求確認。</p></section>
<section class="section comparison-section"><div class="wrap"><div class="comparison-intro"><div><p class="eyebrow">02 / KNOW THE DIFFERENCE</p><h2>看見差異，<br>才能安心選擇。</h2></div><div><p>比較組合屋，從每一個部位開始。<br>將材料、施工與報價範圍放在相同條件下，一起看清楚。</p>${link('comparison.html','了解組合屋差異')}</div></div>${comparisonTable(true)}</div></section>
<section class="section wrap"><div class="advantage-layout"><figure>${photo('interior','自然光進入木質室內')}<figcaption>DETAILS MAKE THE DIFFERENCE.</figcaption></figure><div><p class="eyebrow">03 / OUR APPROACH</p><h2>看得見的簡潔。<br>看不見的用心。</h2><p>空間的價值，藏在每天使用的細節裡。<br>從規劃到實現，讓每一個選擇都有依據。</p>${link('product.html','產品與結構')}</div></div>${features()}</section>
<section class="section process-section"><div class="wrap">${title('04 / THE PROCESS','每一步，都清楚。', '<p>從一個想法，到一個可以生活的空間。</p>')}${processBlock()}</div></section>
<section class="section wrap contact-layout"><div><p class="eyebrow">05 / LET’S TALK</p><h2>下一個空間，<br>從您的想法開始。</h2><p>不論已有基地，或還在評估方向，<br>都可以先整理需求，再一起往前走。</p>${link('contact.html','了解場勘準備')}<p class="contact-mark">EASY GO<br><span>BUILD WITH CLARITY.</span></p></div>${form()}</section>`);
pages.product=shell('product','產品介紹',`${pageHead('PRODUCT & STRUCTURE','把空間做好。<br>從每一個細節開始。','從結構、生產到配置，認識一個空間如何成形。')}<section class="section wrap"><div class="two-col"><div class="structure-panel">${structure}<p class="note">分層概念示意，實際構造依個案設計圖說確認。</p></div><div><p class="eyebrow">01 / STRUCTURE</p><h2>外觀之下，<br>有完整的思考。</h2><p>柱樑、樓板、屋頂與基礎相互配合。先釐清用途、基地及環境條件，再決定適合的構造與材料。</p><ul class="line-list"><li><strong>柱樑與接合</strong><span>材質、尺寸及構件接合方式</span></li><li><strong>樓板與支撐</strong><span>使用需求與樓板系統配置</span></li><li><strong>圍護與基礎</strong><span>隔熱、防水與基地工程整合</span></li></ul></div></div>${features()}</section><section class="section process-section"><div class="wrap">${title('02 / PRODUCTION','從規劃，到交付。')}${processBlock()}<p class="note">生產與施工內容、順序及時程，以正式圖說與合約確認。</p></div></section><section class="section wrap">${title('03 / SPACE & BUDGET','先確定需求，再討論預算。')}<div class="model-grid" id="plans">${[['日常住宅','起居、睡眠與收納','生活人數／房間數／廚衛設備'],['休憩空間','舒適停留與室內外連結','停留方式／開窗／露台需求'],['獨立工作室','專注、接待與彈性使用','設備配置／隔間／電力需求']].map(([t,d,n],i)=>`<article class="model"><span class="eyebrow">MODEL 0${i+1}</span><h3>${t}</h3><p>${d}</p><p class="model-detail">${n}</p><div class="budget">依個案估價 <span>面積與配置確認後提供</span></div>${link('contact.html','討論這個方向')}</article>`).join('')}</div><p class="note">目前未提供定型模型、坪數與正式價格。預算需納入本體、基礎、運輸吊裝、水電及裝修，避免只比較本體單價。</p><div class="inline-callout"><div><h3>差異，需要放在相同條件下比較。</h3><p>從構件到交付範圍，確認每一份報價真正包含什麼。</p></div>${button('comparison.html','查看部位比較',true)}</div></section>${cta()}`);
pages.cases=shell('cases','精選範例',`${pageHead('SELECTED SPACES','空間，承載不同日常。','住宅、休憩或工作，從使用需求出發，找到適合自己的尺度。')}<section class="section wrap"><div class="filters" aria-label="空間用途篩選"><button class="filter" data-filter="all" aria-pressed="true">全部提案</button><button class="filter" data-filter="living" aria-pressed="false">住宅與休憩</button><button class="filter" data-filter="work" aria-pressed="false">工作空間</button></div><p class="note" id="filter-status" role="status">顯示 3 個空間提案</p>${cards()}<p class="note">官方素材照片搭配用途提案；並非已核實案名、面積與施工資料的完工案例。</p>${projects.map((p,i)=>`<article class="case-detail" id="${p.id}"><div class="case-heading"><span class="eyebrow">0${i+1} / ${p.en}</span><div><h2>${p.title}</h2><p>${p.desc}</p></div>${link('contact.html','討論類似空間')}</div>${photo(p.image,p.alt)}<div class="case-specs"><span>規劃方向 <strong>${p.type}</strong></span><span>基地條件 <strong>依現況評估</strong></span><span>面積與預算 <strong>依需求確認</strong></span></div></article>`).join('')}</section>${cta()}`);
pages.contact=shell('contact','申請場勘',`${pageHead('SITE CONSULTATION','先認識基地。<br>再談理想空間。','把需求整理清楚，是規劃的第一步。')}<section class="section wrap contact-layout"><aside><p class="eyebrow">BEFORE WE BEGIN</p><h2>準備好想法，<br>我們一步步討論。</h2><p>可先提供基地所在地區與用途。細節尚未確定，也能從目前的想法開始整理。</p><ul class="line-list"><li><strong>01</strong><span>基地位置、現況照片</span></li><li><strong>02</strong><span>用途、坪數與使用人數</span></li><li><strong>03</strong><span>預算方向、期待時程</span></li><li><strong>04</strong><span>道路、地勢與已知限制</span></li></ul>${link('faq.html','先看看常見問題')}</aside>${form()}</section><section class="section process-section"><div class="wrap">${title('WHAT HAPPENS NEXT','從需求，走向實現。')}${processBlock()}</div></section>`);
pages.about=shell('about','關於我們',`${pageHead('ABOUT EASY GO','簡潔，是選擇。<br>專業，是基礎。','易立構，從使用者的日常出發，思考空間應有的樣子。')}<section class="section wrap"><div class="two-col">${photo('lounge','自然採光下的沙發與木地板起居角落')}<div><p class="eyebrow">OUR PHILOSOPHY</p><h2>把需要的留下。<br>把細節做好。</h2><p>讓設計回應生活，讓結構回應用途。從一個房間到一處居所，我們相信，清楚的溝通與完整的規劃，是好空間的開始。</p><p>簡潔的外觀、實用的配置，以及願意說清楚的細節，構成易立構的空間提案。</p></div></div></section><section class="section process-section"><div class="wrap">${title('BRAND RECORDS','關於品牌，逐步認識。')}<div class="records"><article><span class="eyebrow">01 / MILESTONES</span><h3>品牌大事紀</h3><p>品牌沿革與重要里程碑將依正式資料呈現，建立年份及各階段紀錄待補齊。</p></article><article><span class="eyebrow">02 / PATENTS</span><h3>專利與技術資料</h3><p>專利證書、證號與適用範圍待正式文件確認；目前不提供未經核實的技術認證。</p></article><article><span class="eyebrow">03 / CONTACT</span><h3>與易立構聯繫</h3><p>公司電話、地址及電子信箱待確認。您可以先下載諮詢單，整理基地與使用需求。</p>${link('contact.html','整理諮詢需求')}</article></div></div></section>${cta()}`);
const faqs=[['規劃之前','還沒有土地，可以先了解嗎？','可以先整理用途、希望的空間大小與預算方向。具體設計及施工方案，需要配合基地條件再評估。'],['規劃之前','可以調整格局與外觀嗎？','可提出開窗、隔間、外觀與設備需求，是否適用需依結構、選定系統及基地條件確認。'],['預算與施工','組合屋價格應該怎麼比較？','將面積、材料、基礎、運輸、吊裝、水電與裝修範圍列在同一張清單，確認包含與未包含項目，再比較總體成本。'],['預算與施工','從規劃到完成需要多久？','圖說確認、材料生產、基地工程與現場條件都會影響時程，實際工期需依正式施工範圍確認。'],['場勘與服務','場勘前需要準備什麼？','建議準備基地位置、現況照片、預計用途、人數與預算方向，以及已知道路或施工限制。'],['場勘與服務','下載諮詢單就完成預約了嗎？','尚未。網站目前只在您的裝置產生諮詢單，不送出個人資料或保留預約；正式聯絡與收件資訊需待補齊。'],['照片與案例','網站照片都是已確認的完工案例嗎？','照片選自提供的官方素材，案名與用途為空間設計提案。個別地點、面積與施工資料，需依正式案例文件確認。']];
pages.faq=shell('faq','常見問題',`${pageHead('QUESTIONS & ANSWERS','把問題，說清楚。','關於規劃、預算與場勘，先了解您關心的事。')}<section class="section wrap faq-layout"><aside><p class="eyebrow">QUICK INDEX</p>${[...new Set(faqs.map(x=>x[0]))].map((c,i)=>`<a href="#faq-${i}">${c}<span>↓</span></a>`).join('')}</aside><div>${[...new Set(faqs.map(x=>x[0]))].map((c,i)=>`<section class="faq-group" id="faq-${i}"><h2>${c}</h2>${faqs.filter(x=>x[0]===c).map(([_,q,a])=>`<details><summary>${q}<span aria-hidden="true">＋</span></summary><p>${a}</p></details>`).join('')}</section>`).join('')}</div></section>${cta()}`);
pages.comparison=shell('comparison','組合屋比較',`${pageHead('COMPARE WITH CLARITY','比較，不只看價格。','不論台灣或大陸組合屋，先把規格、文件與交付範圍放在相同條件下。')}<section class="section wrap">${title('01 / COMPONENTS','從部位，理解差異。')}<p class="section-description">目前未提供特定品牌或產品的實測資料，以下列出採購時可逐项核對的重點，並不代表產地或品牌性能排名。</p>${comparisonTable()}<div class="inline-callout"><div><h3>完整報價，應包含哪些內容？</h3><p>本體＋基礎＋運輸吊裝＋水電＋裝修，確認總費用與責任範圍。</p></div>${link('contact.html','整理比較需求')}</div></section><section class="section process-section"><div class="wrap">${title('02 / NEWS & VIDEO','看見現象，也理解條件。')}<div class="two-col"><article class="resource"><span class="eyebrow">NEWS / 案例報導</span><h3>新聞事件，需要完整背景。</h3><p>查看來源、日期、建物規格與施工環境，避免把單一事件推論為整個類別的表現。</p><p class="resource-status">相關新聞來源待提供與核實</p></article><article class="resource"><span class="eyebrow">VIDEO / 結構與風害</span><h3>影片之外，還有設計與施工。</h3><p>風害影片應一併核對風速、基礎固定、施工階段及調查資料，再判讀問題。</p><p class="resource-status">YouTube 影片來源待提供與核實</p></article></div></div></section>${cta()}`);
await mkdir(path.join(root,'dist/client'),{recursive:true});
await mkdir(path.join(root,'dist/server'),{recursive:true});
for(const [name,html] of Object.entries(pages)){
  await writeFile(path.join(root,`${name}.html`),html);
  await writeFile(path.join(root,'dist/client',`${name}.html`),html);
}
for(const name of ['styles.css','reference.css','app.js']) await copyFile(path.join(root,name),path.join(root,'dist/client',name));
await cp(path.join(root,'assets'),path.join(root,'dist/client/assets'),{recursive:true});
await writeFile(path.join(root,'dist/server/index.js'),'export default {async fetch(request, env) {return env.ASSETS.fetch(request)}};\n');
let checked=0;
for(const [name,html] of Object.entries(pages)){
  for(const [,url] of html.matchAll(/(?:href|src)="([^"]+)"/g)){
    if(/^(https?:|data:)/.test(url)) continue;
    const [file,fragment]=url.split('#');
    const target=path.join(root,file||`${name}.html`);await access(target);
    if(fragment && !(await readFile(target,'utf8')).includes(`id="${fragment}"`)) throw new Error(`Missing fragment ${name}: ${url}`);
    checked++;
  }
}
console.log(`Built ${Object.keys(pages).length} pages; verified ${checked} links and assets (${variant}).`);
